datasource.password=mysql
datasource.url=jdbc:mysql://localhost:3306/phone_store?useSSL=false&allowPublicKeyRetrieval=true
datasource.username=root
datasource.maximumPoolSize=4
datasource.driverClassName=com.mysql.cj.jdbc.Driver
jawire.dev.key=2A51838556726CDED45FC952B5892
auth.verify-token.age=30m
notification.verify-url=http://localhost:8080/verify


# ===============================
# 2. EMAIL CONFIGURATION (Gmail)
# ===============================
mail.host=smtp.gmail.com
mail.port=587
mail.username=kamilionbc@gmail.com
# Lưu ý: Dùng App Password 16 ký tự, KHÔNG dùng password đăng nhập
mail.password=mnpr guwb lslv wnun
mail.auth=true
mail.starttls=true