datasource.password=mysql
datasource.url=jdbc:mysql://localhost:3306/phone_store?useSSL=false&allowPublicKeyRetrieval=true
datasource.username=root
datasource.maximumPoolSize=10
datasource.driverClassName=com.mysql.cj.jdbc.Driver